_commit: 0.0.2rc-239-ga084376
_src_path: gh:skeleton-ci/skeleton-python
author: bswck
cli: true
copyright: Bartosz Sławecki
description: Framework for building bots empowering your web presence.
docs: true
email: bartoszpiotrslawecki@gmail.com
github: bswck
license: MIT
package: brandy
precommit: true
pypi: true
pypi_description: Framework for building bots empowering your web presence.
pypi_project: brandy
pypy: false
python: '3.10'
python_until: ''
repo: brandy
rtd: brandy
tests: true
tidelift: false
visibility: public
wip: true
